
# Look for a magic header which should be sent by the CDN
map $http_cdn_access $reroute_to_cdn {
  default "1";
  CDN_ACCESS_KEY "0";
}
#  f019d740dcf4c990caadb24020221430 "0";

server {
  listen        80;
  listen        [::]:80;
  server_name   localhost;

  access_log  /var/log/nginx/host.access.log  main;

  location / {
    root        /usr/share/nginx/html;
    index       index.html index.htm;

    # Redirect everyone except the CDN
    if ($reroute_to_cdn) {
      return 301 $scheme://code.jquery.com$uri/;
    }
  }

  #error_page    404              /404.html;

  # redirect server error pages to the static page /50x.html
  #
  error_page    500 502 503 504  /50x.html;
  location = /50x.html {
    root   /usr/share/nginx/html;
  }
}

# vim: ts=2 sw=2 et
